import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("/Users/ashna/Desktop/Student_Performance_Analysis/Data/StudentsPerformance.csv.xls")
print("Dataset Shape:")
print(df.shape)
print("\nAverage Scores:")
print(df[['math score', 'reading score', 'writing score']].mean())
print("\nHighest Math Score:")
print(df['math score'].max())
print("\nHighest Reading Score:")
print(df['reading score'].max())
print("\nHighest Writing Score:")
print(df['writing score'].max())
print("\nStudents who completed test preparation:")
print(df['test preparation course'].value_counts())
df['math score'].hist()
plt.title("Distribution of Math Scores")
plt.xlabel("Math Score")
plt.ylabel("Number of Students")
plt.savefig("charts/math_scores.png")
plt.show()
print("\nAverage Scores by Gender:")
print(df.groupby('gender')[['math score', 'reading score', 'writing score']].mean())
print("\nAverage Scores by Test Preparation:")
print(df.groupby('test preparation course')[['math score', 'reading score', 'writing score']].mean())
avg_scores = df[['math score', 'reading score', 'writing score']].mean()
avg_scores.plot(kind='bar')
plt.title("Average Scores by Subject")
plt.xlabel("Subjects")
plt.ylabel("Average Score")
plt.savefig("charts/average_scores.png")
plt.show()